[uwsgi]
http = :8011
pythonpath = /usr/local/lib/python3.6/site-packages
wsgi-file = app.py
callable = app
enable-threads = true
workers = 10
threads = 3
lazy-apps = false
master = master
max-requests = 20000000
vacuum = true
listen = 128
reaper = true
